"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.totalCities = exports.provinces = exports.citiesByProvince = exports.indonesiaCities = void 0;
exports.indonesiaCities = [
    { id: 1, province: 'Aceh', name: 'Banda Aceh', type: 'Kota', postalCode: '23000', multiplier: 2.5 },
    { id: 2, province: 'Aceh', name: 'Sabang', type: 'Kota', postalCode: '24410', multiplier: 2.8 },
    { id: 3, province: 'Aceh', name: 'Langsa', type: 'Kota', postalCode: '24400', multiplier: 2.6 },
    { id: 4, province: 'Aceh', name: 'Lhokseumawe', type: 'Kota', postalCode: '24300', multiplier: 2.6 },
    { id: 5, province: 'Aceh', name: 'Subulussalam', type: 'Kota', postalCode: '24882', multiplier: 2.7 },
    { id: 11, province: 'Sumatera Utara', name: 'Medan', type: 'Kota', postalCode: '20000', multiplier: 1.8 },
    { id: 12, province: 'Sumatera Utara', name: 'Binjai', type: 'Kota', postalCode: '20700', multiplier: 1.9 },
    { id: 13, province: 'Sumatera Utara', name: 'Tebing Tinggi', type: 'Kota', postalCode: '20600', multiplier: 2.0 },
    { id: 14, province: 'Sumatera Utara', name: 'Pematangsiantar', type: 'Kota', postalCode: '21100', multiplier: 2.0 },
    { id: 15, province: 'Sumatera Utara', name: 'Tanjungbalai', type: 'Kota', postalCode: '21300', multiplier: 2.1 },
    { id: 16, province: 'Sumatera Utara', name: 'Padang Sidempuan', type: 'Kota', postalCode: '22700', multiplier: 2.2 },
    { id: 17, province: 'Sumatera Utara', name: 'Gunungsitoli', type: 'Kota', postalCode: '22800', multiplier: 2.5 },
    { id: 21, province: 'Sumatera Barat', name: 'Padang', type: 'Kota', postalCode: '25000', multiplier: 2.0 },
    { id: 22, province: 'Sumatera Barat', name: 'Bukittinggi', type: 'Kota', postalCode: '26100', multiplier: 2.1 },
    { id: 23, province: 'Sumatera Barat', name: 'Padang Panjang', type: 'Kota', postalCode: '27100', multiplier: 2.2 },
    { id: 24, province: 'Sumatera Barat', name: 'Payakumbuh', type: 'Kota', postalCode: '26200', multiplier: 2.2 },
    { id: 25, province: 'Sumatera Barat', name: 'Sawahlunto', type: 'Kota', postalCode: '27400', multiplier: 2.3 },
    { id: 26, province: 'Sumatera Barat', name: 'Solok', type: 'Kota', postalCode: '27300', multiplier: 2.2 },
    { id: 27, province: 'Sumatera Barat', name: 'Pariaman', type: 'Kota', postalCode: '25500', multiplier: 2.1 },
    { id: 31, province: 'Riau', name: 'Pekanbaru', type: 'Kota', postalCode: '28000', multiplier: 2.0 },
    { id: 32, province: 'Riau', name: 'Dumai', type: 'Kota', postalCode: '28800', multiplier: 2.2 },
    { id: 41, province: 'Kepulauan Riau', name: 'Batam', type: 'Kota', postalCode: '29400', multiplier: 1.5 },
    { id: 42, province: 'Kepulauan Riau', name: 'Tanjung Pinang', type: 'Kota', postalCode: '29100', multiplier: 2.3 },
    { id: 51, province: 'Jambi', name: 'Jambi', type: 'Kota', postalCode: '36100', multiplier: 2.1 },
    { id: 52, province: 'Jambi', name: 'Sungai Penuh', type: 'Kota', postalCode: '37100', multiplier: 2.3 },
    { id: 61, province: 'Sumatera Selatan', name: 'Palembang', type: 'Kota', postalCode: '30000', multiplier: 1.9 },
    { id: 62, province: 'Sumatera Selatan', name: 'Prabumulih', type: 'Kota', postalCode: '31100', multiplier: 2.0 },
    { id: 63, province: 'Sumatera Selatan', name: 'Pagar Alam', type: 'Kota', postalCode: '31500', multiplier: 2.2 },
    { id: 64, province: 'Sumatera Selatan', name: 'Lubuklinggau', type: 'Kota', postalCode: '31600', multiplier: 2.1 },
    { id: 71, province: 'Bangka Belitung', name: 'Pangkal Pinang', type: 'Kota', postalCode: '33100', multiplier: 2.3 },
    { id: 81, province: 'Bengkulu', name: 'Bengkulu', type: 'Kota', postalCode: '38200', multiplier: 2.2 },
    { id: 91, province: 'Lampung', name: 'Bandar Lampung', type: 'Kota', postalCode: '35100', multiplier: 1.7 },
    { id: 92, province: 'Lampung', name: 'Metro', type: 'Kota', postalCode: '34100', multiplier: 1.8 },
    { id: 101, province: 'DKI Jakarta', name: 'Jakarta Pusat', type: 'Kota', postalCode: '10000', multiplier: 1.0 },
    { id: 102, province: 'DKI Jakarta', name: 'Jakarta Utara', type: 'Kota', postalCode: '14000', multiplier: 1.0 },
    { id: 103, province: 'DKI Jakarta', name: 'Jakarta Barat', type: 'Kota', postalCode: '11000', multiplier: 1.0 },
    { id: 104, province: 'DKI Jakarta', name: 'Jakarta Selatan', type: 'Kota', postalCode: '12000', multiplier: 1.0 },
    { id: 105, province: 'DKI Jakarta', name: 'Jakarta Timur', type: 'Kota', postalCode: '13000', multiplier: 1.0 },
    { id: 106, province: 'DKI Jakarta', name: 'Kepulauan Seribu', type: 'Kabupaten', postalCode: '14550', multiplier: 2.0 },
    { id: 111, province: 'Banten', name: 'Tangerang', type: 'Kota', postalCode: '15000', multiplier: 1.1 },
    { id: 112, province: 'Banten', name: 'Tangerang Selatan', type: 'Kota', postalCode: '15300', multiplier: 1.1 },
    { id: 113, province: 'Banten', name: 'Serang', type: 'Kota', postalCode: '42100', multiplier: 1.3 },
    { id: 114, province: 'Banten', name: 'Cilegon', type: 'Kota', postalCode: '42400', multiplier: 1.4 },
    { id: 121, province: 'Jawa Barat', name: 'Bandung', type: 'Kota', postalCode: '40100', multiplier: 1.2 },
    { id: 122, province: 'Jawa Barat', name: 'Bekasi', type: 'Kota', postalCode: '17100', multiplier: 1.1 },
    { id: 123, province: 'Jawa Barat', name: 'Bogor', type: 'Kota', postalCode: '16100', multiplier: 1.2 },
    { id: 124, province: 'Jawa Barat', name: 'Depok', type: 'Kota', postalCode: '16400', multiplier: 1.1 },
    { id: 125, province: 'Jawa Barat', name: 'Cimahi', type: 'Kota', postalCode: '40500', multiplier: 1.2 },
    { id: 126, province: 'Jawa Barat', name: 'Cirebon', type: 'Kota', postalCode: '45100', multiplier: 1.4 },
    { id: 127, province: 'Jawa Barat', name: 'Sukabumi', type: 'Kota', postalCode: '43100', multiplier: 1.3 },
    { id: 128, province: 'Jawa Barat', name: 'Tasikmalaya', type: 'Kota', postalCode: '46100', multiplier: 1.4 },
    { id: 129, province: 'Jawa Barat', name: 'Banjar', type: 'Kota', postalCode: '46300', multiplier: 1.5 },
    { id: 141, province: 'Jawa Tengah', name: 'Semarang', type: 'Kota', postalCode: '50100', multiplier: 1.3 },
    { id: 142, province: 'Jawa Tengah', name: 'Surakarta', type: 'Kota', postalCode: '57100', multiplier: 1.4 },
    { id: 143, province: 'Jawa Tengah', name: 'Magelang', type: 'Kota', postalCode: '56100', multiplier: 1.5 },
    { id: 144, province: 'Jawa Tengah', name: 'Salatiga', type: 'Kota', postalCode: '50700', multiplier: 1.5 },
    { id: 145, province: 'Jawa Tengah', name: 'Pekalongan', type: 'Kota', postalCode: '51100', multiplier: 1.5 },
    { id: 146, province: 'Jawa Tengah', name: 'Tegal', type: 'Kota', postalCode: '52100', multiplier: 1.5 },
    { id: 151, province: 'DI Yogyakarta', name: 'Yogyakarta', type: 'Kota', postalCode: '55100', multiplier: 1.3 },
    { id: 161, province: 'Jawa Timur', name: 'Surabaya', type: 'Kota', postalCode: '60100', multiplier: 1.3 },
    { id: 162, province: 'Jawa Timur', name: 'Malang', type: 'Kota', postalCode: '65100', multiplier: 1.4 },
    { id: 163, province: 'Jawa Timur', name: 'Batu', type: 'Kota', postalCode: '65300', multiplier: 1.5 },
    { id: 164, province: 'Jawa Timur', name: 'Blitar', type: 'Kota', postalCode: '66100', multiplier: 1.5 },
    { id: 165, province: 'Jawa Timur', name: 'Kediri', type: 'Kota', postalCode: '64100', multiplier: 1.5 },
    { id: 166, province: 'Jawa Timur', name: 'Mojokerto', type: 'Kota', postalCode: '61300', multiplier: 1.4 },
    { id: 167, province: 'Jawa Timur', name: 'Madiun', type: 'Kota', postalCode: '63100', multiplier: 1.5 },
    { id: 168, province: 'Jawa Timur', name: 'Pasuruan', type: 'Kota', postalCode: '67100', multiplier: 1.5 },
    { id: 169, province: 'Jawa Timur', name: 'Probolinggo', type: 'Kota', postalCode: '67200', multiplier: 1.6 },
    { id: 171, province: 'Bali', name: 'Denpasar', type: 'Kota', postalCode: '80100', multiplier: 1.6 },
    { id: 181, province: 'Nusa Tenggara Barat', name: 'Mataram', type: 'Kota', postalCode: '83100', multiplier: 1.8 },
    { id: 182, province: 'Nusa Tenggara Barat', name: 'Bima', type: 'Kota', postalCode: '84100', multiplier: 2.0 },
    { id: 191, province: 'Nusa Tenggara Timur', name: 'Kupang', type: 'Kota', postalCode: '85100', multiplier: 2.2 },
    { id: 201, province: 'Kalimantan Barat', name: 'Pontianak', type: 'Kota', postalCode: '78100', multiplier: 2.0 },
    { id: 202, province: 'Kalimantan Barat', name: 'Singkawang', type: 'Kota', postalCode: '79100', multiplier: 2.2 },
    { id: 211, province: 'Kalimantan Tengah', name: 'Palangkaraya', type: 'Kota', postalCode: '73100', multiplier: 2.2 },
    { id: 221, province: 'Kalimantan Selatan', name: 'Banjarmasin', type: 'Kota', postalCode: '70100', multiplier: 2.0 },
    { id: 222, province: 'Kalimantan Selatan', name: 'Banjarbaru', type: 'Kota', postalCode: '70700', multiplier: 2.1 },
    { id: 231, province: 'Kalimantan Timur', name: 'Samarinda', type: 'Kota', postalCode: '75100', multiplier: 2.1 },
    { id: 232, province: 'Kalimantan Timur', name: 'Balikpapan', type: 'Kota', postalCode: '76100', multiplier: 2.0 },
    { id: 233, province: 'Kalimantan Timur', name: 'Bontang', type: 'Kota', postalCode: '75300', multiplier: 2.2 },
    { id: 241, province: 'Kalimantan Utara', name: 'Tarakan', type: 'Kota', postalCode: '77100', multiplier: 2.5 },
    { id: 251, province: 'Sulawesi Utara', name: 'Manado', type: 'Kota', postalCode: '95100', multiplier: 2.3 },
    { id: 252, province: 'Sulawesi Utara', name: 'Bitung', type: 'Kota', postalCode: '95500', multiplier: 2.4 },
    { id: 253, province: 'Sulawesi Utara', name: 'Tomohon', type: 'Kota', postalCode: '95400', multiplier: 2.5 },
    { id: 254, province: 'Sulawesi Utara', name: 'Kotamobagu', type: 'Kota', postalCode: '95700', multiplier: 2.6 },
    { id: 261, province: 'Gorontalo', name: 'Gorontalo', type: 'Kota', postalCode: '96100', multiplier: 2.5 },
    { id: 271, province: 'Sulawesi Tengah', name: 'Palu', type: 'Kota', postalCode: '94100', multiplier: 2.4 },
    { id: 281, province: 'Sulawesi Selatan', name: 'Makassar', type: 'Kota', postalCode: '90100', multiplier: 2.0 },
    { id: 282, province: 'Sulawesi Selatan', name: 'Pare-Pare', type: 'Kota', postalCode: '91100', multiplier: 2.2 },
    { id: 283, province: 'Sulawesi Selatan', name: 'Palopo', type: 'Kota', postalCode: '91900', multiplier: 2.3 },
    { id: 291, province: 'Sulawesi Tenggara', name: 'Kendari', type: 'Kota', postalCode: '93100', multiplier: 2.4 },
    { id: 292, province: 'Sulawesi Tenggara', name: 'Bau-Bau', type: 'Kota', postalCode: '93700', multiplier: 2.6 },
    { id: 301, province: 'Sulawesi Barat', name: 'Mamuju', type: 'Kota', postalCode: '91500', multiplier: 2.5 },
    { id: 311, province: 'Maluku', name: 'Ambon', type: 'Kota', postalCode: '97100', multiplier: 2.8 },
    { id: 312, province: 'Maluku', name: 'Tual', type: 'Kota', postalCode: '97600', multiplier: 3.0 },
    { id: 321, province: 'Maluku Utara', name: 'Ternate', type: 'Kota', postalCode: '97700', multiplier: 2.9 },
    { id: 322, province: 'Maluku Utara', name: 'Tidore Kepulauan', type: 'Kota', postalCode: '97800', multiplier: 3.0 },
    { id: 331, province: 'Papua Barat', name: 'Sorong', type: 'Kota', postalCode: '98400', multiplier: 3.2 },
    { id: 341, province: 'Papua', name: 'Jayapura', type: 'Kota', postalCode: '99100', multiplier: 3.5 },
];
exports.citiesByProvince = exports.indonesiaCities.reduce((acc, city) => {
    if (!acc[city.province]) {
        acc[city.province] = [];
    }
    acc[city.province].push(city);
    return acc;
}, {});
exports.provinces = Array.from(new Set(exports.indonesiaCities.map(c => c.province))).sort();
exports.totalCities = exports.indonesiaCities.length;
//# sourceMappingURL=cities.seeder.js.map